# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SubspaceProductAPI.Model.Body1 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t | nil
  }
end

defimpl Poison.Decoder, for: SubspaceProductAPI.Model.Body1 do
  def decode(value, _options) do
    value
  end
end

