# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SubspaceProductAPI.Model.ProtobufAny do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"typeUrl",
    :"value"
  ]

  @type t :: %__MODULE__{
    :"typeUrl" => String.t | nil,
    :"value" => binary() | nil
  }
end

defimpl Poison.Decoder, for: SubspaceProductAPI.Model.ProtobufAny do
  def decode(value, _options) do
    value
  end
end

