# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SubspaceProductAPI.Model.RpcStatus do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"code",
    :"details",
    :"message"
  ]

  @type t :: %__MODULE__{
    :"code" => integer() | nil,
    :"details" => [SubspaceProductAPI.Model.ProtobufAny.t] | nil,
    :"message" => String.t | nil
  }
end

defimpl Poison.Decoder, for: SubspaceProductAPI.Model.RpcStatus do
  import SubspaceProductAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"details", :list, SubspaceProductAPI.Model.ProtobufAny, options)
  end
end

