# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SubspaceProductAPI.Model.V1Accelerator do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"destination_ip",
    :"destination_port",
    :"id",
    :"name",
    :"subspace_ipv4",
    :"subspace_port"
  ]

  @type t :: %__MODULE__{
    :"destination_ip" => String.t | nil,
    :"destination_port" => integer() | nil,
    :"id" => String.t | nil,
    :"name" => String.t | nil,
    :"subspace_ipv4" => String.t | nil,
    :"subspace_port" => integer() | nil
  }
end

defimpl Poison.Decoder, for: SubspaceProductAPI.Model.V1Accelerator do
  def decode(value, _options) do
    value
  end
end

