# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SubspaceProductAPI.Model.V1CreateSipTeleport do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"destination"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"destination" => String.t
  }
end

defimpl Poison.Decoder, for: SubspaceProductAPI.Model.V1CreateSipTeleport do
  def decode(value, _options) do
    value
  end
end

