# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SubspaceProductAPI.Model.V1ListAcceleratorsResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accelerators",
    :"nextPage"
  ]

  @type t :: %__MODULE__{
    :"accelerators" => [SubspaceProductAPI.Model.V1Accelerator.t] | nil,
    :"nextPage" => SubspaceProductAPI.Model.V1NextPage.t | nil
  }
end

defimpl Poison.Decoder, for: SubspaceProductAPI.Model.V1ListAcceleratorsResponse do
  import SubspaceProductAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"accelerators", :list, SubspaceProductAPI.Model.V1Accelerator, options)
    |> deserialize(:"nextPage", :struct, SubspaceProductAPI.Model.V1NextPage, options)
  end
end

