# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SubspaceProductAPI.Model.V1ListSipTeleportResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"nextPage",
    :"sipTeleports"
  ]

  @type t :: %__MODULE__{
    :"nextPage" => SubspaceProductAPI.Model.V1NextPage.t | nil,
    :"sipTeleports" => [SubspaceProductAPI.Model.V1SipTeleportResponse.t] | nil
  }
end

defimpl Poison.Decoder, for: SubspaceProductAPI.Model.V1ListSipTeleportResponse do
  import SubspaceProductAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"nextPage", :struct, SubspaceProductAPI.Model.V1NextPage, options)
    |> deserialize(:"sipTeleports", :list, SubspaceProductAPI.Model.V1SipTeleportResponse, options)
  end
end

