# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SubspaceProductAPI.Model.V1ListProjectsResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"projects",
    :"next_page"
  ]

  @type t :: %__MODULE__{
    :"projects" => [SubspaceProductAPI.Model.V1Project.t] | nil,
    :"next_page" => SubspaceProductAPI.Model.V1NextPage.t | nil
  }
end

defimpl Poison.Decoder, for: SubspaceProductAPI.Model.V1ListProjectsResponse do
  import SubspaceProductAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"projects", :list, SubspaceProductAPI.Model.V1Project, options)
    |> deserialize(:"next_page", :struct, SubspaceProductAPI.Model.V1NextPage, options)
  end
end

