# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SubspaceProductAPI.Model.V1ListSipTeleportResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"sip_teleports",
    :"next_page"
  ]

  @type t :: %__MODULE__{
    :"sip_teleports" => [SubspaceProductAPI.Model.V1SipTeleportResponse.t] | nil,
    :"next_page" => SubspaceProductAPI.Model.V1NextPage.t | nil
  }
end

defimpl Poison.Decoder, for: SubspaceProductAPI.Model.V1ListSipTeleportResponse do
  import SubspaceProductAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"sip_teleports", :list, SubspaceProductAPI.Model.V1SipTeleportResponse, options)
    |> deserialize(:"next_page", :struct, SubspaceProductAPI.Model.V1NextPage, options)
  end
end

