# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SubspaceProductAPI.Model.V1Project do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name",
    :"accelerator_quota",
    :"accelerator_request_port",
    :"globalturn_limit_gb",
    :"sipteleport_quota",
    :"sipteleport_call_quota",
    :"rtpspeed_limit_gb"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"name" => String.t | nil,
    :"accelerator_quota" => integer() | nil,
    :"accelerator_request_port" => boolean() | nil,
    :"globalturn_limit_gb" => integer() | nil,
    :"sipteleport_quota" => integer() | nil,
    :"sipteleport_call_quota" => integer() | nil,
    :"rtpspeed_limit_gb" => integer() | nil
  }
end

defimpl Poison.Decoder, for: SubspaceProductAPI.Model.V1Project do
  def decode(value, _options) do
    value
  end
end

