# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SubspaceProductAPI.Model.V1SipTeleportResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name",
    :"destination",
    :"teleport_entry_points",
    :"status",
    :"date_created",
    :"date_updated"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"name" => String.t | nil,
    :"destination" => String.t | nil,
    :"teleport_entry_points" => [SubspaceProductAPI.Model.V1TeleportAddresses.t] | nil,
    :"status" => SubspaceProductAPI.Model.V1SipTeleportStatus.t | nil,
    :"date_created" => DateTime.t | nil,
    :"date_updated" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: SubspaceProductAPI.Model.V1SipTeleportResponse do
  import SubspaceProductAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"teleport_entry_points", :list, SubspaceProductAPI.Model.V1TeleportAddresses, options)
    |> deserialize(:"status", :struct, SubspaceProductAPI.Model.V1SipTeleportStatus, options)
  end
end

