# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SubspaceProductAPI.Model.V1SipTeleportResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"dateCreated",
    :"dateUpdated",
    :"destination",
    :"id",
    :"status",
    :"teleportEntryPoints",
    :"version"
  ]

  @type t :: %__MODULE__{
    :"dateCreated" => DateTime.t | nil,
    :"dateUpdated" => DateTime.t | nil,
    :"destination" => String.t | nil,
    :"id" => String.t | nil,
    :"status" => SubspaceProductAPI.Model.V1SipTeleportStatus.t | nil,
    :"teleportEntryPoints" => [SubspaceProductAPI.Model.V1TeleportAddresses.t] | nil,
    :"version" => integer() | nil
  }
end

defimpl Poison.Decoder, for: SubspaceProductAPI.Model.V1SipTeleportResponse do
  import SubspaceProductAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"status", :struct, SubspaceProductAPI.Model.V1SipTeleportStatus, options)
    |> deserialize(:"teleportEntryPoints", :list, SubspaceProductAPI.Model.V1TeleportAddresses, options)
  end
end

