# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SubspaceProductAPI.Model.V1Session do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"client_ip",
    :"client_port",
    :"subspace_ip",
    :"subspace_port"
  ]

  @type t :: %__MODULE__{
    :"client_ip" => String.t | nil,
    :"client_port" => integer() | nil,
    :"subspace_ip" => String.t | nil,
    :"subspace_port" => integer() | nil
  }
end

defimpl Poison.Decoder, for: SubspaceProductAPI.Model.V1Session do
  def decode(value, _options) do
    value
  end
end

