# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SubspaceProductAPI.Model.V1TeleportAddresses do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"address",
    :"transport_type"
  ]

  @type t :: %__MODULE__{
    :"address" => String.t | nil,
    :"transport_type" => SubspaceProductAPI.Model.V1TransportType.t | nil
  }
end

defimpl Poison.Decoder, for: SubspaceProductAPI.Model.V1TeleportAddresses do
  import SubspaceProductAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"transport_type", :struct, SubspaceProductAPI.Model.V1TransportType, options)
  end
end

