# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SubspaceProductAPI.Model.V1WebRtcCdnResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"iceServers",
    :"ttl"
  ]

  @type t :: %__MODULE__{
    :"iceServers" => [SubspaceProductAPI.Model.V1WebRtcCdnServer.t] | nil,
    :"ttl" => integer() | nil
  }
end

defimpl Poison.Decoder, for: SubspaceProductAPI.Model.V1WebRtcCdnResponse do
  import SubspaceProductAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"iceServers", :list, SubspaceProductAPI.Model.V1WebRtcCdnServer, options)
  end
end

